---
extends: default

rules:
  line-length:
    max: 200
    level: warning
  indentation:
    indent-sequences: false
  comments:
    min-spaces-from-content: 1
  comments-indentation: {}
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
  trailing-spaces:
    level: warning
