// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for DonationType.
const (
	Clothing DonationType = "clothing"
	Food     DonationType = "food"
	Money    DonationType = "money"
)

// DonationDistribution defines model for DonationDistribution.
type DonationDistribution struct {
	Date *time.Time `json:"date,omitempty"`

	// Description (optional) description of the distribution
	Description *string `json:"description,omitempty"`

	// DonationId id of the donation this is associated with
	DonationId int `json:"donation_id"`

	// Id id of the distribution (to be populated by the service)
	Id *int `json:"id,omitempty"`

	// Quantity the amount distributed from the donation
	Quantity int64 `json:"quantity"`

	// Type The type of donation
	Type DonationType `json:"type"`
}

// DonationInventory defines model for DonationInventory.
type DonationInventory struct {
	Report *[]TypeDonationStatus `json:"report,omitempty"`
}

// DonationRegistration defines model for DonationRegistration.
type DonationRegistration struct {
	Date *time.Time `json:"date,omitempty"`

	// Description (optional) description of the donation
	Description *string `json:"description,omitempty"`

	// Id id of the donation (to be populated by the service)
	Id *int64 `json:"id,omitempty"`

	// Name name of the donor; all donations under the same name are attributed to the same person (for simplicity)
	Name string `json:"name"`

	// Quantity the amount given for the donation
	Quantity int64 `json:"quantity"`

	// Type The type of donation
	Type DonationType `json:"type"`
}

// DonationStatus defines model for DonationStatus.
type DonationStatus struct {
	Distributions []DonationDistribution `json:"distributions"`
	Donation      DonationRegistration   `json:"donation"`
}

// DonationType The type of donation
type DonationType string

// DonorReport defines model for DonorReport.
type DonorReport struct {
	Report *[]DonorSummary `json:"report,omitempty"`
}

// DonorSummary defines model for DonorSummary.
type DonorSummary struct {
	Donations []struct {
		// Quantity the amount given for the donation
		Quantity *int64 `json:"quantity,omitempty"`

		// QuantityDistributed the amount distributed for the donation
		QuantityDistributed *int64 `json:"quantity_distributed,omitempty"`

		// Type The type of donation
		Type *DonationType `json:"type,omitempty"`
	} `json:"donations"`

	// Name name of the donor; all donations under the same name are attributed to the same person (for simplicity)
	Name string `json:"name"`
}

// TypeDonationStatus defines model for TypeDonationStatus.
type TypeDonationStatus struct {
	Statuses []DonationStatus `json:"statuses"`

	// Type The type of donation
	Type DonationType `json:"type"`
}

// DistributeDonationJSONRequestBody defines body for DistributeDonation for application/json ContentType.
type DistributeDonationJSONRequestBody = DonationDistribution

// RegisterDonationJSONRequestBody defines body for RegisterDonation for application/json ContentType.
type RegisterDonationJSONRequestBody = DonationRegistration

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Distribute certain donations
	// (POST /donations/distribute)
	DistributeDonation(w http.ResponseWriter, r *http.Request)
	// Records details of the donations
	// (POST /donations/register)
	RegisterDonation(w http.ResponseWriter, r *http.Request)
	// Generates a donator report for each donor
	// (GET /donations/report/donor)
	GetDonorReport(w http.ResponseWriter, r *http.Request)
	// Generates an inventory report for the current status of donations
	// (GET /donations/report/inventory)
	GetDonationInventoryReport(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DistributeDonation operation middleware
func (siw *ServerInterfaceWrapper) DistributeDonation(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DistributeDonation(w, r)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RegisterDonation operation middleware
func (siw *ServerInterfaceWrapper) RegisterDonation(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterDonation(w, r)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetDonorReport operation middleware
func (siw *ServerInterfaceWrapper) GetDonorReport(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDonorReport(w, r)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetDonationInventoryReport operation middleware
func (siw *ServerInterfaceWrapper) GetDonationInventoryReport(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDonationInventoryReport(w, r)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshallingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshallingParamError) Error() string {
	return fmt.Sprintf("Error unmarshalling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshallingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/donations/distribute", wrapper.DistributeDonation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/donations/register", wrapper.RegisterDonation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/donations/report/donor", wrapper.GetDonorReport)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/donations/report/inventory", wrapper.GetDonationInventoryReport)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9SYX2/bNhDAvwrBDVgCqJKTZnvwXpYtRZGhWIskb0NQMNRZYiGRLHmy5wX+7sNRf23J",
	"jZOsKfoUhSLvjne/+yPfc2lKazRo9Hx+z73MoRTh8cJogcroC+XRqbuKnmndOmPBoYKwKxUI9HdhXCmQ",
	"z8PCK1Ql8Ijj2gKfczqvM76JeApeOmVbUVv/8iMTnkRxzAYvmFkwzIGlQzOmRDfmflTpWLRKOzHNNoa5",
	"8kx5Jrw3UgmElK0U5r1opREycCT7AZEDy9gRGnYHzBpbFUHo3Tps8uCWSsLxpPzPldCocD3WQkdFaSqN",
	"vRpI2cKZcus6POLwjyhtAXx+EvXRUBp/OZvUWa/c8x8dLPic/5D0ICQNBUmLwA3t3Wwi7uBzpRykfP73",
	"lsMbcYOb3HY6zd0nkEgqW3GXegkajVuPcXJgjUN6Ugilf8hAMqyVeo0CK99fjQvnxDqYvdeSK8jIq+Jb",
	"s91HcST2QJwP4O6RgGhRwlg1rQ6UG/crE0XR2eFZpVNwtWraGvYLB0xgRy+a/r0F58n8hXHMq9IWSipc",
	"b5nL/zS5Zhdm0usHpU6mlqAZqfjGORN8+rhkabAewzmoOv7ghJks6qOU6avpofK2EmlfpeDRjtVfuvdN",
	"4+vtoN7kwOgIITiMo65K0lQaDWtOsTRUlGRhMCdQbifIuSB6r7p686w6FGRdV2Up3PrgCtSfGAe3Tact",
	"C7b3PI/8A2hvFXwcdJ7DO9STVD4pwUa+3YX5e6hk04Wi52AqVSa634gSH9bh8RViXzv9H6pgU/4608Z3",
	"oxNKLwypkUajkCEXoRSqIFNibVagzk5/y2gllqYcdWB+0w54mp1/uGTeglQLJet2SUESrDBSFMznUCBF",
	"2rBSaJEBxVS5vreqdl6JecQLJUH74ICaK35uhcyBncYzHvHKkYE5op0nyWq1ikV4GxuXJc1Rn7y7/OPN",
	"X9dvXp3GszjHsgheBVf694vrul/3MvxKZBm4WJkkbEmIHYUBp3fB/uvG/vMPlzziS3C+dsBJPItPTki2",
	"saCFVXzOX8ez+DWPuBWYBxSSDrGkT9+AkfE4TprzojArX0PfqPUoFgtyXmEytspBM6FTlpsVKyuZ7w4q",
	"PqTQoFJETAqLFWVB2Lhb3SPW1iFGMRtVmiioCyoE1icHPYYiRulQz50pn/Ou83Wpw2s6wePvJl23yIEO",
	"1xeWEjnsSz75uiHWkD+t1W7qZPDW6CYrT2ezr65zNzd8JSV4v6gK1nmHQDmb/TyO+aVeikKlTGlbYUhm",
	"3/atgTeZBIdC6T7SBKrI/HAC8PyWzg+gc2FwAPc05BxI41KWAgpV+BFrEfOEoPB9kf/Jh0IejThjR2F4",
	"iBjNDhFrR4eIAcr4eJpCOjpF4NCIMYFXzZVfiL+d0exF+NvVeRh/W2RdhdD6vbE9kC4a45IQebI9gwnA",
	"3oImE8AzUYs3jtUHiR+yR/3bVSeDomDkq26KJQhBLduvchAyr1EbBf4t4HDo/Lpx6NQ8zf37nRJ659Yt",
	"D46DGn74PxSLQd9tNafK20Ks22DIyjnQyOpBYpjMPmKZM5VtvoPXFuI90dj+QeJFIrPzG8iz4zPhqHb6",
	"/oKH9sVt063vxuZ9a4oP8sOsRKHoW3s7DtdlmreT90DB5nbzXwAAAP//yjHH5XMUAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
