// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for DonationType.
const (
	Clothing DonationType = "clothing"
	Food     DonationType = "food"
	Money    DonationType = "money"
)

// DonationDistribution defines model for DonationDistribution.
type DonationDistribution struct {
	Date *time.Time `json:"date,omitempty"`

	// Description (optional) description of the distribution
	Description *string `json:"description,omitempty"`

	// DonationId id of the donation this is associated with
	DonationId int `json:"donation_id"`

	// Id id of the distribution (to be populated by the service)
	Id *int `json:"id,omitempty"`

	// Quantity the amount distributed from the donation
	Quantity int `json:"quantity"`

	// Type The type of donation
	Type DonationType `json:"type"`
}

// DonationInventory defines model for DonationInventory.
type DonationInventory map[string][]DonationStatus

// DonationRegistration defines model for DonationRegistration.
type DonationRegistration struct {
	Date *time.Time `json:"date,omitempty"`

	// Description (optional) description of the donation
	Description *string `json:"description,omitempty"`

	// Id id of the donation (to be populated by the service)
	Id *int `json:"id,omitempty"`

	// Name name of the donor; all donations under the same name are attributed to the same person (for simplicity)
	Name string `json:"name"`

	// Quantity the amount given for the donation
	Quantity int `json:"quantity"`

	// Type The type of donation
	Type DonationType `json:"type"`
}

// DonationStatus defines model for DonationStatus.
type DonationStatus struct {
	Distributions []DonationDistribution `json:"distributions"`
	Donation      DonationRegistration   `json:"donation"`
}

// DonationSummary defines model for DonationSummary.
type DonationSummary struct {
	// Quantity the amount given for the donation
	Quantity int `json:"quantity"`

	// QuantityDistributed the amount distributed for the donation
	QuantityDistributed int `json:"quantity_distributed"`
}

// DonationType The type of donation
type DonationType string

// DonorReport defines model for DonorReport.
type DonorReport struct {
	Report *[]DonorSummary `json:"report,omitempty"`
}

// DonorSummary defines model for DonorSummary.
type DonorSummary struct {
	Donations map[string]DonationSummary `json:"donations"`

	// Name name of the donor; all donations under the same name are attributed to the same person (for simplicity)
	Name string `json:"name"`
}

// DistributeDonationJSONRequestBody defines body for DistributeDonation for application/json ContentType.
type DistributeDonationJSONRequestBody = DonationDistribution

// RegisterDonationJSONRequestBody defines body for RegisterDonation for application/json ContentType.
type RegisterDonationJSONRequestBody = DonationRegistration

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Distribute certain donations
	// (POST /donations/distribute)
	DistributeDonation(w http.ResponseWriter, r *http.Request)
	// Records details of the donations
	// (POST /donations/register)
	RegisterDonation(w http.ResponseWriter, r *http.Request)
	// Generates a donator report for each donor
	// (GET /donations/report/donors)
	GetDonorReport(w http.ResponseWriter, r *http.Request)
	// Generates an inventory report for the current status of donations
	// (GET /donations/report/inventory)
	GetDonationInventoryReport(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DistributeDonation operation middleware
func (siw *ServerInterfaceWrapper) DistributeDonation(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DistributeDonation(w, r)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RegisterDonation operation middleware
func (siw *ServerInterfaceWrapper) RegisterDonation(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterDonation(w, r)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetDonorReport operation middleware
func (siw *ServerInterfaceWrapper) GetDonorReport(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDonorReport(w, r)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetDonationInventoryReport operation middleware
func (siw *ServerInterfaceWrapper) GetDonationInventoryReport(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDonationInventoryReport(w, r)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshallingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshallingParamError) Error() string {
	return fmt.Sprintf("Error unmarshalling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshallingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/donations/distribute", wrapper.DistributeDonation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/donations/register", wrapper.RegisterDonation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/donations/report/donors", wrapper.GetDonorReport)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/donations/report/inventory", wrapper.GetDonationInventoryReport)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RYb2/bthP+Kgf+fsBaQJWctHvjvVm6FEWGYg2SvCuCgqHOEguJVMmTPS/wdx+O+mvL",
	"TpxuzbZXUSjy7vg8z/2R74WyZWUNGvJifi+8yrGU4fHcGknamnPtyem7mp95vXK2Qkcaw65UEvLfhXWl",
	"JDEPC69IlygiQesKxVzweZOJTSRS9MrpqjO19a94YcOTLF7C6AXYBVCOkI7D2Ge6DfezTqemddqbabcB",
	"5dqD9iC9t0pLwhRWmvLBtDaEGTq2/YjJUWTwgizcIVS2qotg9G4dNnl0S63w5V77X2tpSNN66oWPytLW",
	"hgY3mMLC2XLrOiIS+LssqwLF/CQa2NCGRCRKbXRZl+HV1Huzci/+73Ah5uJ/ySCJpNVD0onhhvduNpFw",
	"+LXWDlMx/7QFfWtudKfb3qe9+4KK2GVn7sIs0ZB14eYyTXUjgMstiWnC0h8b4DVJqv1wLSGdk+vR/9Mg",
	"rjBjaOU/LfCByonZIzV9hPgeUMlUGUaWOHXMqyPX1v0Esij6KDzUJkXXOOatYb90CJJ6AZMd3lfoPAe/",
	"sA68LqtCK03rrWDFrzY3cG73Yn5U9mR6iQbYxb8mbQK6T8uXVt1TkY5K0NNzZqvC78mcHq0j7W0l1KFi",
	"IaKdqB+8d12WsqkS2xf/a9w/mgCd+c+j4nt8kX6ywx2o+ssdCOQhxG5adW5HepMj8BFO33EOGFb5J1Fa",
	"g+sQpuVKrgpLOSfZ7Z6sO+fMv8LKOprS4vr1Y4VoXcfxRIAHavdwYpoOXSl6qK0c1U0mMQ0h/BeK4/6K",
	"M8AzVRAf0WZh+WbKGpIq0Iil1AVTEhu7Qv3m9OeMV2Jly0nbEzfdaGXg7PICfIVKL7RqehRfREJhlSzA",
	"51gQo2GhlEZmyPfWbmhoupsPYhGJQis0PmDeYC/OKqlyhNN4JiJROw4wJ6rmSbJarWIZ3sbWZUl71Ccf",
	"Ln5599v1u1en8SzOqSwCs+hK/3Fx3TTJwYZfySxDF2ubhC0J46spQP4hxH/dxn92eSEisUTnGwBO4ll8",
	"csK2bYVGVlrMxet4Fr8Wkagk5UF/SU9DMiR10LL1NBXWWVHYlW+E0br1JBcLBq+wGaxyNCBNCrldQVmr",
	"fHc68EFmo/oRgZIV1ayUsHG3METQVR1gziYFLgruggtJzclRQWfGON2aOS8Vc9G3GTwfSg/LEz29tem6",
	"kxyacH1ZsdjDvuSLb7pPk5/f1tc2TTb4yrIS2Mbp7OS7+9zNDV8rhd4v6gJ6dFgob2azKedvZQotQCGX",
	"fVfwRliCQkdSm4FnlqnM/LjZenHL50eSc6FHo/s2wTlU1qWQIkld+InSIvAsQOmHMviDD6UumqgMXoSu",
	"EwE3nQi6nhMBkopf7tcgH92nv3EQU/1dtVd+JvXtTEHPor5dn99JfVeBfn+Q/yMVyDNCEtQRAMlwjwrf",
	"o+E40YNs7FsHzUkWGQek/+gLmCVZAAPaT5WsVNTL7pMZpcobPU7U8R5pPNJMyJr9nWT1bp7A0Y/7OLow",
	"hM5wK0K3RAfvnLNuh63DEIZmvIXJ0bTp8Zf7Y8yNGnnnOdW+KuS6o07VzqEhrjBU+3F98BFkztZV+zW7",
	"rjA+wN32LwrPwuPOjxjPzOYeWLtvjgfwPMTypl/fDetjF7gP9sOoxsQNk0U3sTZ9QnTD8cjB5nbzZwAA",
	"AP//H598PmwUAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
